# -*- coding: utf-8 -*-
"""
多语言配置文件
支持中文和英文两种语言
"""

LANGUAGES = {
    'zh': {
        # 通用
        'app_title': '数据可视化程序',
        'welcome': '欢迎',
        'logout': '注销',
        'login': '登录',
        'register': '注册',
        'username': '用户名',
        'password': '密码',
        'confirm_password': '确认密码',
        'login_success': '登录成功',
        'register_success': '注册成功',
        'login_failed': '登录失败',
        'register_failed': '注册失败',
        
        # 模式切换
        'classic_mode': '经典模式',
        'dashboard_mode': '仪表盘模式',
        'switch_to_classic': '切换到经典模式',
        'switch_to_dashboard': '切换到仪表盘模式',
        
        # 数据管理
        'data': '数据',
        'upload_file': '上传文件',
        'select_data_source': '选择数据源',
        'please_select_file': '-- 请选择文件 --',
        'preview': '预览',
        'delete': '删除',
        'no_data_files': '暂无数据文件',
        'support_formats': '支持 Excel 和 CSV 格式',
        
        # 字段
        'fields': '字段',
        'dimensions': '维度',
        'measures': '度量',
        
        # 可视化类型
        'visualization_type': '选择可视化类型',
        'list_table': '清单表',
        'cross_table': '交叉表',
        'line_chart': '折线图',
        'area_chart': '面积图',
        'pie_chart': '饼图',
        'bar_chart': '柱状图',
        'waterfall_chart': '瀑布图',
        'scatter_chart': '散点图',
        'combo_single': '单Y联合图',
        'combo_dual': '双Y联合图',
        'wordcloud': '词云图',
        'sunburst': '旭日图',
        'map': '地图',
        
        # 配置
        'rows': '行',
        'columns': '列',
        'values': '值',
        'x_axis': 'X轴',
        'y_axis': 'Y轴',
        'x_axis_dimension': 'X轴（维度）',
        'y_axis_measure': 'Y轴（度量）',
        'x_axis_measure': 'X轴（度量）',
        'region_field': '地区字段',
        'group_field': '分组字段',
        'text_field': '文本字段',
        'weight_field': '权重字段',
        'dimension_field': '维度字段',
        'measure_field': '度量字段',
        
        # 提示
        'drag_field_here': '将字段拖到此处',
        'drag_dimension_here': '将维度字段拖到此处',
        'drag_measure_here': '将度量字段拖到此处',
        'drag_region_here': '将地区字段拖到此处',
        'drag_text_here': '将文本字段拖到此处',
        'drag_weight_here': '将权重字段拖到此处（可选）',
        'optional': '（可选）',
        
        # 主题
        'theme': '主题',
        'purple': '紫色',
        'blue': '蓝色',
        'green': '绿色',
        'orange': '橙色',
        'red': '红色',
        'pink': '粉色',
        'cyan': '青色',
        'sunset': '日落渐变',
        'ocean': '海洋渐变',
        'forest': '森林渐变',
        
        # 按钮
        'generate_table': '生成表格',
        'generate_chart': '生成图表',
        'download_chart': '下载图表',
        'download_html': '下载HTML',
        
        # 图表创建区
        'chart_create_zone': '图表创建区',
        'drag_file_to_create': '将左侧文件拖到这里开始创建可视化',
        
        # 仪表盘
        'dashboard': '仪表盘',
        'widgets': '部件',
        'widget_config': '部件配置',
        'chart_type': '图表类型',
        'select_chart_type': '-- 选择图表类型 --',
        'widget_text': '文本',
        'widget_image': '图片',
        'widget_chart': '图形',
        
        # 消息
        'uploading': '正在上传文件...',
        'upload_success': '上传成功',
        'upload_failed': '上传失败',
        'generating': '正在生成...',
        'generate_success': '生成成功',
        'generate_failed': '生成失败',
        'deleting': '正在删除...',
        'delete_success': '删除成功',
        'delete_failed': '删除失败',
        'confirm_delete': '确认删除该文件吗？',
        'please_select_file_first': '请先选择一个数据文件',
        'no_chart_to_download': '没有可下载的图表',
        
        # 其他
        'total_rows': '总行数',
        'displayed_rows': '显示行数',
        'save': '保存',
        'cancel': '取消',
        'close': '关闭',
        'edit': '编辑',
        'settings': '设置',
        
        # JavaScript中的文本
        'uploading_file': '正在上传文件...',
        'file_uploaded': '文件已上传',
        'generating_table': '正在生成表格...',
        'generating_chart': '正在生成图表...',
        'generating_sunburst': '正在生成旭日图...',
        'generating_wordcloud': '正在生成词云图...',
        'generating_combo': '正在生成联合图...',
        'loading_data': '正在加载数据...',
        'please_select_file_first': '请先选择一个文件',
        'please_select_data_file': '请先选择一个数据文件',
        'please_select_dimension_xaxis': '请选择维度字段（X轴）',
        'please_select_xy_axis': '请选择X轴和Y轴字段',
        'chart_creation_zone': '图表创建区',
        'drag_file_to_create': '将左侧文件拖到这里开始创建可视化',
        'drag_widget_here': '请从上方拖拽部件到此处创建仪表盘',
        'select_data_file_first': '请先选择一个数据文件',
        'select_file': '选择文件',
        'no_preview_available': '无预览',
        'confirm_delete_file': '确认删除该文件吗？',
        'file_deleted': '文件已删除',
        'delete_file': '删除文件',
        'preview_data': '预览数据',
        'supports_widgets': '支持清单表、交叉表、图形、文本和图片',
        'usage_tips': '操作提示',
        'tip_click_widget': '点击部件 - 在左侧配置',
        'tip_drag_resize': '拖拽拖拉 - 移动部件',
        'tip_resize_widget': '拖拽边缘 - 调整大小',
        'tip_hover_delete': '悬停显示 - 关闭图标和删除按钮',
        
        # 词云图相关
        'text_field': '文本字段',
        'weight_field_optional': '权重字段（可选）',
        'drag_text_field_required': '将文本字段拖到此处（必填）',
        'drag_weight_field_optional': '将数值字段拖到此处作为权重（可选）',
        'wordcloud_shape': '词云形状',
        'shape_rectangle': '矩形（默认）',
        'shape_circle': '圆形',
        'shape_cloud': '云形',
        'shape_star': '星形',
        'shape_heart': '心形',
        'shape_diamond': '菱形',
        'generate_wordcloud': '生成词云图',
        'select_text_field': '请选择文本字段',
        
        # 部件占位符文本
        'click_widget_to_config': '点击此部件进行配置',
        'click_widget_config_chart': '点击此部件配置图表',
        'click_widget_add_text': '点击此部件添加文本',
        'click_widget_upload_image': '点击此部件上传图片',
        'select_file_drag_field_to_create': '选择数据文件并拖拽字段开始创建表格',
        
        # 部件配置面板
        'chart_config': '图表配置',
        'chart_type': '图表类型',
        'select_chart_type': '-- 选择图表类型 --',
        'please_select_chart_type_first': '请先选择图表类型',
        'theme': '主题',
        'generate_chart_btn': '生成图表',
        'select_image': '选择图片',
        'no_file_chosen': '未选择文件',
        'upload_image': '上传图片',
        'please_select_image': '请选择图片文件',
        'list_table_config': '清单表配置',
        'cross_table_config': '交叉表配置',
        'text_config': '文本配置',
        'row_fields': '行字段',
        'column_fields': '列字段',
        'value_fields': '值字段',
        'drag_field_here': '拖拽字段到此处',
        'generate_list_table': '生成清单表',
        'generate_cross_table': '生成交叉表',
        'from_left_drag_dim_to_row': '从左侧拖拽列拖拽维度字段到行字段区域',
        'select_text_field_label': '选择文本字段',
        'select_weight_field': '选择权重字段（可选）',
        'x_axis_field': 'X轴字段',
        'y_axis_field': 'Y轴字段',
        'select_x_axis': '-- 选择X轴字段 --',
        'select_y_axis': '-- 选择Y轴字段 --',
        'province_field': '省份字段',
        'value_field': '值字段',
        'select_province_field': '-- 选择省份字段 --',
        'select_value_field': '-- 选择值字段 --',
        'dimension_field': '维度字段（行）',
        'measure_field': '度量字段（值）',
        'select_dimension_field': '-- 选择维度字段 --',
        'select_measure_field': '-- 选择度量字段 --',
        'dimension_x_axis': '维度（X轴）',
        'measure_fields': '度量字段',
        'add_measure': '添加度量',
        'no_measures': '暂无度量字段',
        'properties': '属性',
        
        # 图表类型名称
        'line_chart': '折线图',
        'bar_chart': '柱状图',
        'area_chart': '面积图',
        'pie_chart': '饼图',
        'waterfall_chart': '瀑布图',
        'scatter_chart': '散点图',
        'wordcloud': '词云图',
        'map': '地图',
        'sunburst': '旭日图',
        'combo_single': '单Y联合图',
        'combo_dual': '双Y联合图',
        
        # 更多配置选项
        'no_weight': '-- 不使用权重 --',
        'no_grouping': '-- 不分组 --',
        'select_dimension': '-- 选择维度 --',
        'drag_dimension_here': '拖拽维度字段到此处',
        'drag_measure_here': '拖拽度量字段到此处',
        'dimension_hierarchy': '维度字段（层级）',
        'group_field_optional': '分组字段（可选）',
    },
    'en': {
        # Common
        'app_title': 'Data Visualization Program',
        'welcome': 'Welcome',
        'logout': 'Logout',
        'login': 'Login',
        'register': 'Register',
        'username': 'Username',
        'password': 'Password',
        'confirm_password': 'Confirm Password',
        'login_success': 'Login successful',
        'register_success': 'Registration successful',
        'login_failed': 'Login failed',
        'register_failed': 'Registration failed',
        
        # Mode Switch
        'classic_mode': 'Classic Mode',
        'dashboard_mode': 'Dashboard Mode',
        'switch_to_classic': 'Switch to Classic Mode',
        'switch_to_dashboard': 'Switch to Dashboard Mode',
        
        # Data Management
        'data': 'Data',
        'upload_file': 'Upload File',
        'select_data_source': 'Select Data Source',
        'please_select_file': '-- Please Select File --',
        'preview': 'Preview',
        'delete': 'Delete',
        'no_data_files': 'No Data Files',
        'support_formats': 'Supports Excel and CSV formats',
        
        # Fields
        'fields': 'Fields',
        'dimensions': 'Dimensions',
        'measures': 'Measures',
        
        # Visualization Types
        'visualization_type': 'Select Visualization Type',
        'list_table': 'List Table',
        'cross_table': 'Cross Table',
        'line_chart': 'Line Chart',
        'area_chart': 'Area Chart',
        'pie_chart': 'Pie Chart',
        'bar_chart': 'Bar Chart',
        'waterfall_chart': 'Waterfall Chart',
        'scatter_chart': 'Scatter Chart',
        'combo_single': 'Single Y Combo',
        'combo_dual': 'Dual Y Combo',
        'wordcloud': 'Word Cloud',
        'sunburst': 'Sunburst',
        'map': 'Map',
        
        # Configuration
        'rows': 'Rows',
        'columns': 'Columns',
        'values': 'Values',
        'x_axis': 'X-Axis',
        'y_axis': 'Y-Axis',
        'x_axis_dimension': 'X-Axis (Dimension)',
        'y_axis_measure': 'Y-Axis (Measure)',
        'x_axis_measure': 'X-Axis (Measure)',
        'region_field': 'Region Field',
        'group_field': 'Group Field',
        'text_field': 'Text Field',
        'weight_field': 'Weight Field',
        'dimension_field': 'Dimension Field',
        'measure_field': 'Measure Field',
        
        # Hints
        'drag_field_here': 'Drag field here',
        'drag_dimension_here': 'Drag dimension field here',
        'drag_measure_here': 'Drag measure field here',
        'drag_region_here': 'Drag region field here',
        'drag_text_here': 'Drag text field here',
        'drag_weight_here': 'Drag weight field here (optional)',
        'optional': '(Optional)',
        
        # Themes
        'theme': 'Theme',
        'purple': 'Purple',
        'blue': 'Blue',
        'green': 'Green',
        'orange': 'Orange',
        'red': 'Red',
        'pink': 'Pink',
        'cyan': 'Cyan',
        'sunset': 'Sunset Gradient',
        'ocean': 'Ocean Gradient',
        'forest': 'Forest Gradient',
        
        # Buttons
        'generate_table': 'Generate Table',
        'generate_chart': 'Generate Chart',
        'download_chart': 'Download Chart',
        'download_html': 'Download HTML',
        
        # Chart Create Zone
        'chart_create_zone': 'Chart Creation Zone',
        'drag_file_to_create': 'Drag file from left to start visualization',
        
        # Dashboard
        'dashboard': 'Dashboard',
        'widgets': 'Widgets',
        'widget_config': 'Widget Configuration',
        'chart_type': 'Chart Type',
        'select_chart_type': '-- Select Chart Type --',
        'widget_text': 'Text',
        'widget_image': 'Image',
        'widget_chart': 'Chart',
        
        # Messages
        'uploading': 'Uploading file...',
        'upload_success': 'Upload successful',
        'upload_failed': 'Upload failed',
        'generating': 'Generating...',
        'generate_success': 'Generation successful',
        'generate_failed': 'Generation failed',
        'deleting': 'Deleting...',
        'delete_success': 'Deletion successful',
        'delete_failed': 'Deletion failed',
        'confirm_delete': 'Confirm delete this file?',
        'please_select_file_first': 'Please select a data file first',
        'no_chart_to_download': 'No chart to download',
        
        # Others
        'total_rows': 'Total Rows',
        'displayed_rows': 'Displayed Rows',
        'save': 'Save',
        'cancel': 'Cancel',
        'close': 'Close',
        'edit': 'Edit',
        'settings': 'Settings',
        
        # JavaScript texts
        'uploading_file': 'Uploading file...',
        'file_uploaded': 'File uploaded',
        'generating_table': 'Generating table...',
        'generating_chart': 'Generating chart...',
        'generating_sunburst': 'Generating sunburst chart...',
        'generating_wordcloud': 'Generating word cloud...',
        'generating_combo': 'Generating combo chart...',
        'loading_data': 'Loading data...',
        'please_select_file_first': 'Please select a file first',
        'please_select_data_file': 'Please select a data file first',
        'please_select_dimension_xaxis': 'Please select dimension field (X-axis)',
        'please_select_xy_axis': 'Please select X-axis and Y-axis fields',
        'chart_creation_zone': 'Chart Creation Zone',
        'drag_file_to_create': 'Drag file from left to start visualization',
        'drag_widget_here': 'Drag widgets from above to create dashboard',
        'select_data_file_first': 'Please select a data file first',
        'select_file': 'Select File',
        'no_preview_available': 'No Preview',
        'confirm_delete_file': 'Confirm delete this file?',
        'file_deleted': 'File deleted',
        'delete_file': 'Delete File',
        'preview_data': 'Preview Data',
        'supports_widgets': 'Supports Lists, Cross Tables, Charts, Text and Images',
        'usage_tips': 'Usage Tips',
        'tip_click_widget': 'Click widget - Configure in left panel',
        'tip_drag_resize': 'Drag & Drop - Move widgets',
        'tip_resize_widget': 'Drag edges - Resize widgets',
        'tip_hover_delete': 'Hover - Show close icon and delete button',
        
        # Word cloud related
        'text_field': 'Text Field',
        'weight_field_optional': 'Weight Field (Optional)',
        'drag_text_field_required': 'Drag text field here (Required)',
        'drag_weight_field_optional': 'Drag numeric field here as weight (Optional)',
        'wordcloud_shape': 'Word Cloud Shape',
        'shape_rectangle': 'Rectangle (Default)',
        'shape_circle': 'Circle',
        'shape_cloud': 'Cloud',
        'shape_star': 'Star',
        'shape_heart': 'Heart',
        'shape_diamond': 'Diamond',
        'generate_wordcloud': 'Generate Word Cloud',
        'select_text_field': 'Please select a text field',
        
        # Widget placeholder texts
        'click_widget_to_config': 'Click this widget to configure',
        'click_widget_config_chart': 'Click this widget to configure chart',
        'click_widget_add_text': 'Click this widget to add text',
        'click_widget_upload_image': 'Click this widget to upload image',
        'select_file_drag_field_to_create': 'Select data file and drag fields to create table',
        
        # Widget configuration panel
        'chart_config': 'Chart Configuration',
        'chart_type': 'Chart Type',
        'select_chart_type': '-- Select Chart Type --',
        'please_select_chart_type_first': 'Please select chart type first',
        'theme': 'Theme',
        'generate_chart_btn': 'Generate Chart',
        'select_image': 'Select Image',
        'no_file_chosen': 'No file chosen',
        'upload_image': 'Upload Image',
        'please_select_image': 'Please select an image file',
        'list_table_config': 'List Table Configuration',
        'cross_table_config': 'Cross Table Configuration',
        'text_config': 'Text Configuration',
        'row_fields': 'Row Fields',
        'column_fields': 'Column Fields',
        'value_fields': 'Value Fields',
        'drag_field_here': 'Drag field here',
        'generate_list_table': 'Generate List Table',
        'generate_cross_table': 'Generate Cross Table',
        'from_left_drag_dim_to_row': 'Drag dimension fields from left to row field area',
        'select_text_field_label': 'Select Text Field',
        'select_weight_field': 'Select Weight Field (Optional)',
        'x_axis_field': 'X-axis Field',
        'y_axis_field': 'Y-axis Field',
        'select_x_axis': '-- Select X-axis Field --',
        'select_y_axis': '-- Select Y-axis Field --',
        'province_field': 'Province Field',
        'value_field': 'Value Field',
        'select_province_field': '-- Select Province Field --',
        'select_value_field': '-- Select Value Field --',
        'dimension_field': 'Dimension Field (Rows)',
        'measure_field': 'Measure Field (Values)',
        'select_dimension_field': '-- Select Dimension Field --',
        'select_measure_field': '-- Select Measure Field --',
        'dimension_x_axis': 'Dimension (X-axis)',
        'measure_fields': 'Measure Fields',
        'add_measure': 'Add Measure',
        'no_measures': 'No measure fields',
        'properties': 'Properties',
        
        # Chart type names
        'line_chart': 'Line Chart',
        'bar_chart': 'Bar Chart',
        'area_chart': 'Area Chart',
        'pie_chart': 'Pie Chart',
        'waterfall_chart': 'Waterfall Chart',
        'scatter_chart': 'Scatter Chart',
        'wordcloud': 'Word Cloud',
        'map': 'Map',
        'sunburst': 'Sunburst Chart',
        'combo_single': 'Single Y Combo Chart',
        'combo_dual': 'Dual Y Combo Chart',
        
        # More configuration options
        'no_weight': '-- No Weight --',
        'no_grouping': '-- No Grouping --',
        'select_dimension': '-- Select Dimension --',
        'drag_dimension_here': 'Drag dimension field here',
        'drag_measure_here': 'Drag measure field here',
        'dimension_hierarchy': 'Dimension Field (Hierarchy)',
        'group_field_optional': 'Group Field (Optional)',
    }
}

def get_text(key, lang='zh'):
    """获取指定语言的文本"""
    return LANGUAGES.get(lang, LANGUAGES['zh']).get(key, key)

def get_all_texts(lang='zh'):
    """获取指定语言的所有文本"""
    return LANGUAGES.get(lang, LANGUAGES['zh'])

